playbooks:
  - id: dev
    name: dev
    prompts: []
    servers:
      - name: context-7
        prompts:
          include: []
        disabled: false
        command: npx
        args:
          - -y
          - "@upstash/context7-mcp"
        env: {}
        type: stdio
      - name: git
        prompts:
          include: []
        disabled: false
        command: uvx
        args:
          - mcp-server-git
        env: {}
        type: stdio
      - name: memory
        prompts:
          include: []
        disabled: false
        command: npx
        args:
          - -y
          - "@modelcontextprotocol/server-memory"
        env: {}
        type: stdio
      - name: sequential-thinking
        prompts:
          include: []
        disabled: false
        command: npx
        args:
          - -y
          - "@modelcontextprotocol/server-sequential-thinking"
        env: {}
        type: stdio
      - name: serena
        prompts:
          include: []
        disabled: false
        command: uvx
        args:
          - --from
          - git+https://github.com/oraios/serena
          - serena
          - start-mcp-server
        env: {}
        type: stdio
