# Colors are from dracula theme, but modified a litle
# https://github.com/dracula/starship/blob/master/starship.toml

right_format = """$cmd_duration"""
palette = "nord"
[ruby]
disabled = true

[rust]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[git_branch]
# style = "bold #ff79c6"
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
stashed = ""
style = "bold green"
format = '([$all_status $ahead_behind]($style))'

[git_metrics]
disabled = true

[aws]
disabled = true
# style = "bold #ffb86c"

[shell]
disabled = true

[cmd_duration]
# style = "bold #f1fa8c"
format = "[$duration]($style)"
min_time = 0

[docker_context]
disabled = true

[character]
# error_symbol = "[➜](bold #ff5555)"
# success_symbol = "[➜](bold #50fa7b)"

[directory]
# style = "bold #50fa7b"

[hostname]
# style = "bold #bd93f9"

[username]
format = "[$user]($style) on "
# style_user = "bold #8be9fd"

[package]
disabled = true

[palettes.nord]
# Polar Night (dark backgrounds)
nord0 = "#2e3440"
nord1 = "#3b4252"
nord2 = "#434c5e"
nord3 = "#4c566a"
# Snow Storm (light foregrounds)
nord4 = "#d8dee9"
nord5 = "#e5e9f0"
nord6 = "#eceff4"
# Frost (blues/cyans)
nord7 = "#8fbcbb"
nord8 = "#88c0d0"
nord9 = "#81a1c1"
nord10 = "#5e81ac"
# Aurora (accent colors)
nord11 = "#bf616a"
nord12 = "#d08770"
nord13 = "#ebcb8b"
nord14 = "#a3be8c"
nord15 = "#b48ead"
# Semantic color mappings for Starship
red = "#bf616a"
orange = "#d08770"
yellow = "#ebcb8b"
green = "#a3be8c"
purple = "#b48ead"
cyan = "#88c0d0"
blue = "#81a1c1"
text = "#eceff4"
subtext1 = "#e5e9f0"
subtext0 = "#d8dee9"
overlay2 = "#4c566a"
overlay1 = "#434c5e"
overlay0 = "#3b4252"
surface2 = "#3b4252"
surface1 = "#3b4252"
surface0 = "#2e3440"
base = "#2e3440"
teal = "#8fbcbb"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
